### ISSUE TITLE
Timeout Sending Metrics

### ISSUE THREAD

**Issue by icpenguins** [newrelic/nri-statsd#11]
## Description
A customer is using the Statsd integration to send A LOT of metric values to New Relic. Although they have been hitting the threshold limits, it is not expected that the client timeout should occur.

```bash
# grep  used: grep -vE "sleeping for|status=429|bad status code 429" UUID-json.log | grep "2020-09"

# a few of these
{"log":"time=\"2020-09-02T05:09:58Z\" level=error msg=\"Sending metrics to backend failed: [newrelic] error POSTing: Post https://metric-api.newrelic.com/metric/v1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)\"\n","stream":"stderr","time":"2020-09-02T05:09:58.343059372Z"}

# a LOT of these
{"log":"time=\"2020-09-02T16:21:55Z\" level=info msg=\"[newrelic] failed request\" body=\"[60 33 68 79 67 84 89 80 69 32 104 
...[omitted for brevity]...
10]\" status=503\n","stream":"stderr","time":"2020-09-02T16:21:55.402442294Z"}
```
## Expected Behavior
The client request should not timeout while waiting for headers.

**Comment by josemore** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution for more than year. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.
