### ISSUE TITLE
Update to gostatsd v35.0.0

### ISSUE THREAD

**Issue by msummers-nr** [newrelic/nri-statsd#27]
## Is your feature request related to a problem? Please describe.
Yes, we need the new `statsdSource` tag for monitoring HCP Consul clusters

## Feature Description
Update to gostatsd v35.0.0

## Describe Alternatives
There are no alternatives

## Additional context
Required for HCP Consul monitoring

## Priority
Blocker

**Comment by davidgit** [comment]
Duplicate of #29
