### ISSUE TITLE
Request for Loadbalancer Adminport for service check

### ISSUE THREAD

**Issue by ORuessel** [newrelic/nri-statsd#46]
### Description
In Kubernetes or other orchestration software with multiple instances of new statsd in a high flexibel environment general statsd docker image support a tcp port to monitor the health of statsd instance.

### Acceptance Criteria
central port with tcp for loadbalancer to create a health check on this

### Describe Alternatives
_A clear and concise description of any alternative solutions or features you've considered_
_Are there examples you could link us to?_

### Dependencies
_Do any other teams or parts of the New Relic product need to be considered?_
_Some common areas: UI, collector, documentation_

### Additional context
_What else should we know about this story that might not fit into the other categories?_

### Estimates
_Please provide initial t-shirt size. S = 1-3 days,  M = 3-5 days (1 week), L = 1-2 weeks (1 sprint)_

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by josemore** [comment]
thanks for submitting this, it seems we'd need to configure the http server for health from gotstatsd:  https://github.com/atlassian/gostatsd#configuring-http-servers

are you able / willing to contribute this change?

**Comment by ORuessel** [comment]
@josemore sorry for the long delay, i forget this request. Yes sure, i am testing. Which configuration for http server you prefer behind a network loadbalancer ?

**Comment by ORuessel** [comment]
I got now time to work on that and create a push request. But i see now, that you has share a different implementation possibility. I will work on this now.
